apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - migrate-job.yaml
  - dags-pvc.yaml
  - dag-sync-deployment.yaml
  - webserver-deployment.yaml
  - scheduler-deployment.yaml
  - triggerer-deployment.yaml
  - logs-pvc.yaml
  - webserver-service.yaml

namespace: airflow

labels:
  - pairs:
      app: airflow
      part-of: gitops-poc
