apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - dag-sync-sidecar.yaml
  - dags-pvc.yaml
  - migrate-job.yaml
  - create-admin-job.yaml
  - webserver-deployment.yaml
  - scheduler-deployment.yaml
  - triggerer-deployment.yaml
  - webserver-service.yaml

namespace: airflow

commonLabels:
  app: airflow
  part-of: gitops-poc
