apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-triggerer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-triggerer
  template:
    metadata:
      labels:
        app: airflow-triggerer
    spec:
      serviceAccountName: airflow
      containers:
        - name: triggerer
          image: apache/airflow:3.0.0-python3.12
          command: ["airflow", "triggerer"]
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secret
          volumeMounts:
            - name: airflow-logs
              mountPath: /home/airflow/logs
            - name: dags
              mountPath: /home/airflow/dags
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "airflow jobs check --job-type TriggererJob"
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 5

      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: dev-logs-local-pvc
        - name: dags
          persistentVolumeClaim:
            claimName: dev-dags-pvc
