apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - service.yaml
  - statefulset.yaml

namespace: mysql

labels:
  - pairs:
      app: mysql
      part-of: gitops-poc
