apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespaces.yaml
  - 02-serviceaccounts-rbac-core.yaml
  - 03-rbac-cross-namespace.yaml
  - 04-configmaps-airflow.yaml
  - 05-job-db-migrate.yaml
  - 06-pvc-dags.yaml
  - 07-pvc-logs.yaml
  - 08-deploy-dag-sync.yaml
  - 09-deploy-webserver.yaml
  - 10-deploy-scheduler.yaml
  - 11-deploy-triggerer.yaml
  - 12-deploy-dag-processor.yaml
  - 13-services.yaml
  - 15-kube-state-metrics.yaml
  - 16-prometheus.yaml
  - 17-grafana.yaml
