apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube-state-metrics.yaml
  - prometheus.yaml
  - grafana.yaml

labels:
  - pairs:
      app: monitoring
      part-of: gitops-poc
    includeSelectors: false
