apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: kube-ops-view
  namespace: airflow-core
spec:
  type: ClusterIP
  selector:
    app: kube-ops-view
  ports:
    - name: http
      port: 80
      targetPort: 8080
