apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/UtkarshChakrwarti/k8-argo-cd.git
    path: k8s/airflow/overlays/dev
    targetRevision: feature/multi-namespace-executor
  destination:
    server: https://kubernetes.default.svc
    # No namespace â€” resources span airflow-core and airflow-user
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
