apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/UtkarshChakrwarti/Codespace_PLAY.git
    path: k8s/monitoring/overlays/dev
    targetRevision: feature/multi-namespace-executor
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
