apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: airflow

namePrefix: dev-

labels:
  - pairs:
      environment: dev

replicas:
  - name: airflow-webserver
    count: 1
  - name: airflow-scheduler
    count: 1
  - name: airflow-triggerer
    count: 1
  - name: airflow-dag-sync
    count: 1
  - name: airflow-dag-processor
    count: 1
