apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: airflow

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
  - name: airflow-webserver
    count: 1
  - name: airflow-scheduler
    count: 1
  - name: airflow-triggerer
    count: 1
